name: Run Hello World and LS

on:
  workflow_call: 
    # Este workflow solo puede ser llamado por otros repositorios o flujos

jobs:
  run-inline-script:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código para tener acceso a los archivos
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Ejecución de comandos de consola
      - name: Exec HolaMundo y LS
        run: |
          echo "Hola Mundo"
          pwd
          ls -lah
          echo "Fin del Script"